#ifndef INIT_H_
#define INIT_H_

#include <hwlib.h>

enum {
  ERR_SYSTEM_INIT_OK = 0,
  ERR_SYSTEM_INIT_FPGA = 1,
  ERR_SYSTEM_INIT_GLOBAL_TIMER,
  ERR_SYSTEM_INIT_INTERRUPTS,
  ERR_SYSTEM_INIT_MMU,
  ERR_SYSTEM_INIT_CACHES,
  ERR_SYSTEM_INIT_PMU,
  ERR_SYSTEM_INIT_TIMER,
  ERR_SYSTEM_INIT_QSPI,
  ERR_SYSTEM_INIT_DMA,
  ERR_SYSTEM_INIT_UART
};

ALT_STATUS_CODE system_init(void);

ALT_STATUS_CODE system_uninit(void);

#endif
